extends:
  - 'eslint:recommended'
  - 'xo-space'
  - 'xo-space/esnext'
  - 'xo-space/browser'
  - 'prettier'

parserOptions:
  ecmaVersion: 2019
  sourceType: module

env:
  browser: true
  commonjs: true
  es6: true
  node: true
  serviceworker: true
  shared-node-browser: true

rules:
  comma-dangle:
    - error
    - only-multiline
  capitalized-comments:
    - off
  object-curly-spacing:
    - error
    - always
  operator-linebreak:
    - error
    - before
