---
  extends:
    - 'eslint:recommended'
    - 'xo-space'
    - 'xo-space/esnext'
    - 'xo-space/browser'

  parserOptions:
    ecmaVersion: 2017
    sourceType: module

  env:
    browser: true
    node: true
    es6: true
    serviceworker: true

  rules:
    array-bracket-spacing:
      - error
      - always
    object-curly-spacing:
      - error
      - always
    capitalized-comments:
      - off
    no-console:
      - off
