---
  extends:
    - 'eslint:recommended'

  parserOptions:
    ecmaVersion: 6
    sourceType: module

  env:
    browser: true
    node: true
    es6: true

  rules:
    # best practices section
    array-callback-return: error
    block-scoped-var: error
    consistent-return: error
    curly: error
    default-case: error
    dot-location:
      - error
      - property
    dot-notation: error
    eqeqeq: error
    no-alert: error
    no-div-regex: error
    no-else-return: error
    no-empty-function: error
    no-eq-null: error
    no-eval: error
    no-extend-native: error
    no-extra-bind: error
    no-extra-label: error
    no-floating-decimal: error
    no-global-assign: error
    no-implicit-coercion: error
    no-implicit-globals: error
    no-implied-eval: error
    no-iterator: error
    no-labels: error
    no-lone-blocks: error
    no-loop-func: error
    no-multi-spaces: error
    no-multi-str: error
    no-new-func: error
    no-new-wrappers: error
    no-new: error
    no-octal-escape: error
    no-param-reassign: error
    no-proto: error
    no-return-assign: error
    no-script-url: error
    no-self-compare: error
    no-sequences: error
    no-throw-literal: error
    no-unmodified-loop-condition: error
    no-unused-expressions: error
    no-useless-call: error
    no-useless-concat: error
    no-useless-escape: error
    no-void: error
    no-with: error
    vars-on-top: error
    wrap-iife: error
    yoda: error

    # Variables section
    no-label-var: error
    no-shadow-restricted-names: error
    no-shadow: error
    no-undef-init: error
    no-undefined: error
    no-use-before-define: error

    # Stylistic Issues section
    array-bracket-spacing:
      - error
      - always
    block-spacing: error
    brace-style: error
    camelcase:
      - error
      - properties: never
    comma-dangle: error
    comma-spacing: error
    comma-style: error
    computed-property-spacing: error
    consistent-this: error
    eol-last: error
    func-call-spacing: error
    func-names: warn
    func-style:
      - warn
      - expression
    indent:
      - error
      - 2
      - SwitchCase: 1
    key-spacing: error
    keyword-spacing: error
    linebreak-style: error
    lines-around-comment: warn
    max-depth: warn
    max-lines: warn
    max-len:
      - warn
      - 120
    max-nested-callbacks: warn
    max-params: warn
    max-statements-per-line: warn
    max-statements:
      - warn
      - 30
    new-cap: warn
    new-parens: error
    newline-after-var: warn
    no-array-constructor: error
    no-bitwise: error
    no-lonely-if: warn
    no-multiple-empty-lines: warn
    no-nested-ternary: error
    no-new-object: error
    no-plusplus: error
    no-tabs: error
    no-trailing-spaces: error
    no-underscore-dangle: warn
    no-unneeded-ternary: warn
    no-whitespace-before-property: error
    object-curly-newline: error
    object-curly-spacing:
      - error
      - always
    one-var:
      - error
      - never
    operator-assignment: error
    operator-linebreak: error
    quote-props:
      - error
      - as-needed
    quotes:
      - error
      - single
      - avoid-escape
    semi-spacing: error
    semi: error
    space-before-blocks: error
    space-before-function-paren: error
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops: error
    spaced-comment: warn
    unicode-bom: error
    wrap-regex: error

    # ECMAScript 6 / ES2015 Section
    arrow-body-style: error
    arrow-parens: error
    arrow-spacing: error
    generator-star-spacing: warn
    no-confusing-arrow: warn
    no-duplicate-imports: error
    no-useless-computed-key: warn
    no-useless-constructor: warn
    no-useless-rename: error
    no-var: error
    object-shorthand: error
    prefer-arrow-callback: warn
    prefer-const: error
    prefer-reflect: warn
    prefer-rest-params: warn
    prefer-spread: warn
    prefer-template: error
    rest-spread-spacing: error
    template-curly-spacing: error
    yield-star-spacing: error
