options:
  merge-default-rules: true

files:
  ignore:
    - 'src/scss/vendor/*.scss'

rules:
  class-name-format:
    - 1
    - convention: hyphenatedbem
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  nesting-depth:
    - 1
    - max-depth: 4
  mixins-before-declarations:
    - 1
    - exclude: [ 'mediaquery', 'attention' ]
  no-color-literals:
    - 1
    - allow-rgba: true
    - allow-map-identifiers: false
    - allow-variable-identifiers: false
  force-pseudo-nesting: 0
  leading-zero: 0
  no-color-keywords: 0
  property-sort-order: 0
  space-around-operator: 0
