files:
  ignore:
    - 'src/styles/3-vendor/**/*.scss'

# use the default settings to keep this file small
options:
  merge-default-rules: true

rules:
  # BEM all the things
  class-name-format:
    - 1
    - convention: hyphenatedbem
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem

  # those mixins do not have to be used before any other declarations
  mixins-before-declarations:
    - 1
    - exclude: ['mediaquery', 'attention']

  # allow leading zero values like 0.2rem or 0.01em
  leading-zero: 0

  # do not sort properties by name
  property-sort-order: 0

  # allow importing of *.scss
  clean-import-paths: 0

  # allow nested attribute and pseudo-selectors, this makes stuff
  # more readable for humans and allows some edge-case-nesting issues,
  force-pseudo-nesting: 0
  force-attribute-nesting: 0

  # allow stuff like 1/2 or 1/4
  space-around-operator: 0

  # allow warnings for better sass-maps debugging
  no-warn: 0
