# use the default settings to keep this file small
options:
  merge-default-rules: true

rules:
  # BEM all the things
  class-name-format:
    - 1
    - convention: hyphenatedbem
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem

  # sassception! allow a maximum nesting depth of 4 levels deep
  nesting-depth:
    - 1
    - max-depth: 4

  # those mixins do not have to be used before any other declarations
  mixins-before-declarations:
    - 1
    - exclude: [ 'mediaquery', 'attention' ]

  # allow non-leading zero values like .2rem or .4rem
  leading-zero: 0

  # do not sort properties by name
  property-sort-order: 0

  # allow nested attribute and pseudo-selectors, this makes stuff
  # more readable for humans and allow some edge-case-nesting issues,
  # but still force element nesting, so the nesting-depth-rule makes sense
  force-pseudo-nesting: 0
  force-attribute-nesting: 0

  # allow stuff like 1/2 or 1/4
  space-around-operator: 0

  # allow warnings for better sass-maps debugging
  no-warn: 0

  # ignore broken warning
  no-color-keywords: 0
