status: wip

context:
  modifiers: ''
  href: '#'
  text: Linktext
  icon: false
  title: false
  attributes: false

variants:
  - name: with-icon
    context:
      text: Link with an icon
      icon: default
      modifiers: 'link--with-icon'
