status: wip

context:
  showTitle: false
  title: 'You can also find me on:'
  items:
    - icon: mastodon
      title: 'Profile on mastodon.social'
      url: 'https://mastodon.social/@webgefrickel'
    - icon: twitter
      title: 'Profile on Twitter'
      url: 'https://twitter.com/webgefrickel'
    - icon: github
      title: 'Profile on GitHub'
      url: 'https://github.com/webgefrickel'
